# Generated by Django 5.1.7 on 2025-09-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_alter_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
    ]
