# Generated by Django 5.1.7 on 2025-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='google_refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
