# Generated by Django 5.1.7 on 2025-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
