# Generated by Django 5.1.7 on 2025-09-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_google_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='google_access_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_refresh_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='google_token_expiry',
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
